<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetUserByIdAuth.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetUserByLoginAuth.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetProfileInfo.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetDek.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetPublicEncryptionInfo.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetChangePasswordData.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\GetRecoveryKeys.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\ExistUserByLogin.sql" />
    <EmbeddedResource Include="Persistence\Repositories\Users\Sql\SearchUsers.sql" />
  </ItemGroup> 

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Dapper" />
     <PackageReference Include="Microsoft.Extensions.Http" />
     <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\infrastructure\Shared.Dapper\Shared.Dapper.csproj" />
    <ProjectReference Include="..\..\..\shared\infrastructure\Shared.EntityFramework\Shared.EntityFramework.csproj" />
    <ProjectReference Include="..\..\..\shared\infrastructure\Shared.Messaging\Shared.Messaging.csproj" />
    <ProjectReference Include="..\..\..\shared\infrastructure\Shared.Redis\Shared.Redis.csproj" />
    <ProjectReference Include="..\Nexus.UserManagement.Service.Application\Nexus.UserManagement.Service.Application.csproj" />
    <ProjectReference Include="..\Nexus.UserManagement.Service.Domain\Nexus.UserManagement.Service.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nexus.UserManagement.Service.Integration.Tests" />
  </ItemGroup>
</Project>
