// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.UserManagement.Service.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.UserManagement.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20260912173642_AddFriendshipCode")]
    partial class AddFriendshipCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Dek", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("dek_type");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_deks_UserId");

                    b.ToTable("deks", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("genders", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_outbox_messages_pending")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextRetryAt"), new[] { "OccurredOnUtc", "EventType", "Content", "RetryCount", "Error" });

                    b.HasIndex("RetryCount")
                        .HasDatabaseName("IX_outbox_messages_retry_count")
                        .HasFilter("retry_count > 0");

                    b.HasIndex("EventType", "OccurredOnUtc")
                        .HasDatabaseName("IX_outbox_messages_event_type_occurred");

                    b.ToTable("outbox_messages", "outbox");
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.RecoveryKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("KeyHint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hint");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("crypto_version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_recovery_keys_UserId");

                    b.ToTable("recovery_keys", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("statuses", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_key");

                    b.Property<DateTime?>("DateEntry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_entry");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_registration");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.Property<string>("FriendshipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("friendship_code")
                        .UseCollation("case_insensitive");

                    b.Property<Guid?>("IdCountry")
                        .HasColumnType("uuid")
                        .HasColumnName("id_country");

                    b.Property<Guid?>("IdGender")
                        .HasColumnType("uuid")
                        .HasColumnName("id_gender");

                    b.Property<Guid>("IdStatus")
                        .HasColumnType("uuid")
                        .HasColumnName("id_status");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login")
                        .UseCollation("case_insensitive");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "FriendshipCode" }, "IX_Users_FriendshipCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "IX_Users_Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.UserAuthenticator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_authenticators_UserId");

                    b.ToTable("user_authenticators", (string)null);

                    b.HasDiscriminator<int>("Method");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.EmailAuthenticator", b =>
                {
                    b.HasBaseType("Nexus.UserManagement.Service.Domain.Models.UserAuthenticator");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.SrpAuthenticator", b =>
                {
                    b.HasBaseType("Nexus.UserManagement.Service.Domain.Models.UserAuthenticator");

                    b.Property<string>("AsymmetricKeyId")
                        .HasColumnType("text")
                        .HasColumnName("srp_asymmetric_key_id");

                    b.Property<int?>("CryptoVersion")
                        .HasColumnType("integer")
                        .HasColumnName("srp_crypto_version");

                    b.Property<string>("EncryptedVerifier")
                        .HasColumnType("text")
                        .HasColumnName("srp_encrypted_verifier");

                    b.Property<string>("EncryptedVerifierWrapKey")
                        .HasColumnType("text")
                        .HasColumnName("srp_encrypted_verifier_wrapKey");

                    b.Property<int?>("KeyWrapVersion")
                        .HasColumnType("integer")
                        .HasColumnName("srp_key_wrap_version");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("srp_login");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("srp_salt");

                    b.Property<int?>("SrpVersion")
                        .HasColumnType("integer")
                        .HasColumnName("srp_version");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.Dek", b =>
                {
                    b.HasOne("Nexus.UserManagement.Service.Domain.Models.User", null)
                        .WithMany("Deks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.RecoveryKey", b =>
                {
                    b.HasOne("Nexus.UserManagement.Service.Domain.Models.User", null)
                        .WithMany("RecoveryKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.UserAuthenticator", b =>
                {
                    b.HasOne("Nexus.UserManagement.Service.Domain.Models.User", null)
                        .WithMany("UserAuthenticators")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.UserRoles", b =>
                {
                    b.HasOne("Nexus.UserManagement.Service.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.UserManagement.Service.Domain.Models.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.UserManagement.Service.Domain.Models.User", b =>
                {
                    b.Navigation("Deks");

                    b.Navigation("RecoveryKeys");

                    b.Navigation("UserAuthenticators");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
