<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="WireMock.Net" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="DistributedLock.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\services\Authentication\Nexus.Authentication.Application\Nexus.Authentication.Application.csproj" />
    <ProjectReference Include="..\..\..\src\services\Authentication\Nexus.Authentication.Domain\Nexus.Authentication.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\services\Authentication\Nexus.Authentication.Infrastructure\Nexus.Authentication.Infrastructure.csproj" />
    <ProjectReference Include="..\..\shared\Shared.Test.Cache\Shared.Test.Cache.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Nexus.Authentication.Integration.Tests</RootNamespace>
    <AssemblyName>Nexus.Authentication.Integration.Tests</AssemblyName>
  </PropertyGroup>

</Project>