<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3d4740b2-c9e0-4337-97b9-8a4918f7c465</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\contracts\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\..\..\shared\web\Shared.Web\Shared.Web.csproj" />
    <ProjectReference Include="..\Nexus.Authentication.Application\Nexus.Authentication.Application.csproj" />
    <ProjectReference Include="..\Nexus.Authentication.Infrastructure\Nexus.Authentication.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Nexus.Authentication.Api</RootNamespace>
    <AssemblyName>Nexus.Authentication.Api</AssemblyName>
  </PropertyGroup>

</Project>
