<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Crossdyne.Security.Srp.Server" />
    <PackageReference Include="Crossdyne.Security.Cryptography" />
    <PackageReference Include="Crossdyne.Toolkit" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="DistributedLock.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\abstractions\Shared.Abstractions\Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\shared\contracts\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\validations\Shared.Validations\Shared.Validations.csproj" />
    <ProjectReference Include="..\Nexus.Authentication.Domain\Nexus.Authentication.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Nexus.Authentication.Application</RootNamespace>
    <AssemblyName>Nexus.Authentication.Application</AssemblyName>
  </PropertyGroup>

</Project>
