<Project Sdk="Microsoft.NET.Sdk.Web">

 <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0940725e-2610-4d9e-b5b1-f9b9afa54f0f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\..\..\shared\web\Shared.Web\Shared.Web.csproj" />
    <ProjectReference Include="..\Nexus.UserManagement.Application\Nexus.UserManagement.Application.csproj" />
    <ProjectReference Include="..\Nexus.UserManagement.Infrastructure\Nexus.UserManagement.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Nexus.UserManagement.Api</RootNamespace>
    <AssemblyName>Nexus.UserManagement.Api</AssemblyName>
  </PropertyGroup>

</Project>
